name: Build Compose Desktop App

on:
  push:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build Jar and Installer
        run: |
          ./gradlew composeApp:packageUberJarForCurrentOS
          ./gradlew composeApp:packageDistributionForCurrentOS

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: compose-desktop-jar
          path: composeApp/build/compose/jars/*.jar

      - name: Upload Installer Deb
        uses: actions/upload-artifact@v4
        with:
          name: compose-desktop-installer
          path: composeApp/build/compose/binaries/main/deb/*.deb

  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install dependencies
        run: |
          dnf install -y git java-21-openjdk-devel rpm-build

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build RPM
        run: |
          chmod +x gradlew
          ./gradlew composeApp:packageDistributionForCurrentOS

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: compose-desktop-installer-rpm
          path: composeApp/build/compose/binaries/main/rpm/*.rpm
